volumes:
  mongo_vol:
    external: true

services:
  # web_frontend:
  #   build: ./web_frontend
  #   environment:
  #     - RTTP_API_URL=localhost:8080
  #   ports:
  #     - 3000:3000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./api:/app

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_vol:/data/db
    environment:
      - DATABASE_URL=mongo://username:password@mongo_vol
